### ISSUE TITLE
Map returns undefined values with never versions

### ISSUE THREAD

**Issue by driescroons** [typestack/class-transformer#1256]
I've got the following code that I set up for testing purposes:
```
@Exclude()
class Transformer {
  @Expose()
  @IsString({ each: true })
  public map!: Map<string, string>;
}

const obj = {
  map: new Map([
    ["1", "123"],
    ["2", "123"],
    ["3", "123"]
  ])
};

let data = plainToClass(Transformer, obj);
console.log(data);
```

Ever since `0.4.1`, the values of the map return undefined (after moving to `plainToInstance`).

The following printscreen is the result of using version `0.4.1`:
![image](https://user-images.githubusercontent.com/27679518/176068661-1ceb1826-ec6b-45db-9c0d-12c2bf8a6a47.png)

The following printscreen is the result of using`0.4.0`:
![image](https://user-images.githubusercontent.com/27679518/176068391-132a31df-f7f9-4478-9f5f-1d93e9725751.png)

As you can see, the values are *not* undefined. 

Did the syntax of validating a map change? Or is there something wrong?
Following link is the CSB for testing: https://codesandbox.io/s/busy-kilby-7e8z73?file=/src/index.ts

**Comment by patil-milind** [comment]
This same issue is also reproducible in the latest version 0.5.1 for the function `plainToInstance`.

**Comment by CodyTseng** [comment]
issue: #596 PR: #374 

```ts
// ...
if (this.transformationType === TransformationType.PLAIN_TO_CLASS) {
  subValue = value[valueKey];
}
// ...
```

I don't know why it changed to this 😂.

Maybe the maintainers think `plain object` should be a simple `JSON object`. Like this:

```ts
@Exclude()
class Transformer {
  @Expose()
  @Type(() => String)
  public map!: Map<string, string>;
}

const obj = {
  map: {
    '1': '123',
    '2': '123',
    '3': '123',
  }
};

const data = plainToInstance(Transformer, obj);
console.log(data);
```

Output:

```
Transformer {
  map: Map(3) { '1' => '123', '2' => '123', '3' => '123' }
}
```

**Comment by driescroons** [comment]
I was trying to have a map of type `Map<string, object[]>` with automatically [generated docs](https://github.com/epiphone/routing-controllers-openapi). I've since then switched back to a regular object to get the proper result. For people running into this issue, this is how I fixed it:
```
  @Expose()
  @IsObject()
  @JSONSchema({
    type: "object",
    properties: {
      "{id}": {
        type: "array",
        items: {
          $ref: `#/components/schemas/${OtherClassTransformerClass.name}`,
        },
      },
    },
  })
  public collections!: { [key: string]: OtherClassTransformerClass[] };
```

**Comment by victor-shelepen** [comment]
It seems the functionality that is described here is not supported. There is a comment with a workaround solution. [Nested map?](https://github.com/typestack/class-transformer/issues/1364#issuecomment-1683991877)

**Comment by 1nVitr0** [comment]
This is still an issue. I havent looked at the underlying code, but the values seem to be lost in the transform. When using a transformer, you can see that the `obj` property still contains the values, but `value` doesnt:

```ts
@Transform(({ key, obj, value }) => {
  console.log('value', value);
  console.log('obj[key]', obj[key]);

  return obj[key];
})
@Expose()
@Type(() => String)
test: Map<string, string> = new Map<string, string>([
    ["a", "a"],
    ["b", "b"],
]);
```

Results in the output:

```shell
value: Map(2) { "a": => undefined, "b" => undefined }
obj[key]: Map(2) { "a": => "a", "b" => "b" }
```

I current use a "fix" using a transformer that returns `obj[key]`:

```ts
export const TransformMap = () => Transform(({ obj, key }) => obj[key]);

@Expose()
@Type(() => String)
@TransformMap()
test: Map<string, string> = new Map<string, string>([
    ["a", "a"],
    ["b", "b"],
]);
```
